
FROM ubuntu:22.04

# update yum
RUN apt-get -y update
RUN apt-get -y install libhts-dev python3-dev python3-pip git gcc


# copy in existing repository folder
COPY majiq_repository /root/majiq_repository

# install majiq
WORKDIR /root/majiq_repository
RUN pip3 install --no-cache-dir -U pip
RUN pip3 install --no-cache-dir ./voila
RUN pip3 install --no-cache-dir ./majiq
RUN rm -rf /root/majiq_repository

CMD []

# To build image: go to some temporary directory and copy id_rsa used for bitbucket into it, then
# $ docker build -t majiq_voila -f /path/to/this/Dockerfile .
# To run loaded image: docker run majiq_voila majiq --help
# To run loaded image: docker run majiq_voila -v /path/to/voila/data/files:/mnt -p 5010:5010 voila view /mnt --host 0.0.0.0 -p 5010 -j4
# note that you may not see the line "Serving on 0.0.0.0:5010" for voila view some reason, but it will work anyway